### PR TITLE
Testing rh-nfv-int/nfv-example-cnf-deploy/pull/11

### PR DESCRIPTION
**Pull request by tonyskapunk**
This tests https://github.com/rh-nfv-int/nfv-example-cnf-deploy/pull/11

### CODE REVIEW

**Comment by tonyskapunk** [comment]
The last failure was on a later step, so the change rh-nfv-int/nfv-example-cnf-deploy#11 has been validated.

The error is strange as is expecting for `testpmd-lb-operator` to be installed, but it is already installed:
```
$ oc -n example-cnf get csv
NAME                                DISPLAY                      VERSION   REPLACES   PHASE
cnf-app-mac-operator.v0.2.6         CNF App MAC Fetch Operator   0.2.6                Succeeded
performance-addon-operator.v4.7.4   Performance Addon Operator   4.7.4                Succeeded
testpmd-lb-operator.v0.2.5          LoadBalancer                 0.2.5                Succeeded
```

The code in question is: https://github.com/rh-nfv-int/nfv-example-cnf-deploy/blob/197830841cc4ade1794719c05927725550d60ba6/roles/example-cnf-app/tasks/sub.yaml#L53-L66

**Comment by krsacme** [comment]
```
task path: /home/dciteam/github/example-cnf-config-pr27-25e74b5d283ff3974ab1f45d04f08849/example-cnf-config/testpmd/hooks/cluster6/nfv-example-cnf-deploy/roles/example-cnf-catalog/tasks/main.yml:26
fatal: [jumphost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: Unable to look up a name or access an attribute in template string ({{ skopeo_digest.stdout | from_json | json_query('Digest') }}).\nMake sure your variable name does not contain invalid characters like '-': the JSON object must be str, bytes or bytearray, not 'AnsibleUndefined'\n\nThe error appears to be in '/home/dciteam/github/example-cnf-config-pr27-25e74b5d283ff3974ab1f45d04f08849/example-cnf-config/testpmd/hooks/cluster6/nfv-example-cnf-deploy/roles/example-cnf-catalog/tasks/main.yml': line 26, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Get index digest\n  ^ here\n"}
```

Looks like the error is with the digest changes of deploy scripts.

**Comment by tonyskapunk** [comment]
Thanks for taking some time to look at it @krsacme , I think the error you mentioned was the first attempt, it was fixed on the 2nd attempt, where it failed with being unable to find `testpmd-lb-operator` but I looked at the time and it was running, I'll keep digging on it today.

**Comment by tonyskapunk** [comment]
The error is due to the fact that `testpmd-lb-operator` csv name is `testpmd-lb-operator.v0.2.5` and that does not match the expected `testpmd-lb-operator.{{ operator_version }}` in https://github.com/rh-nfv-int/nfv-example-cnf-deploy/blob/197830841cc4ade1794719c05927725550d60ba6/roles/example-cnf-app/tasks/sub.yaml#L52

Seems like the `operator_version` is tightly coupled among operators, currently `testpmd-lb-operator` is not in `v0.2.6` yet, the index was built with `v0.2.5` hence that's installed (https://github.com/rh-nfv-int/nfv-example-cnf-index/blob/master/CHANGELOG.md#026---2021-07-01)

I can bump `testpmd-lb-operator` version (https://github.com/rh-nfv-int/testpmd-lb-operator/blob/master/CHANGELOG.md) to be aligned to the rest, then I'll have to build a new index so we can use it accordingly, but it would be nice to not to have to depend so much in the same operator version.

@krsacme what are your thoughts? are you ok with me bumping the version of `testpmd-lb-operator`?

**Comment by krsacme** [comment]
> @krsacme what are your thoughts? are you ok with me bumping the version of `testpmd-lb-operator`?

Yes, that would be the agreed flow to keep all operator versions the same, even though it is not changed. Go ahread.

**Pull request closed without merging**
