### PR TITLE
Define MCP error in example-cnf

### PR DESCRIPTION
**Pull request by tkrishtop**
build-depends: 25097
build-depends: 25098

### CODE REVIEW

**Comment by ramperher** [comment]
@tkrishtop you also need to do the change here:

```
testpmd/hooks/pre-run.yml:        name: wait-mcp
```

**Comment by tkrishtop** [comment]
> @tkrishtop you also need to do the change here:
> 
> ```
> testpmd/hooks/pre-run.yml:        name: wait-mcp
> ```

thanks for the catch @ramperher, added it.

**Review by ramperher — APPROVED** [review]
Thanks!

**Comment by tonyskapunk** [comment]
I'm merging since there is no dependency as we're only defining vars in here.

**Pull request merged**
