### PR TITLE
Update cnf_app_networks and packet_generator_networks to use multiple SRIOV nets

### PR DESCRIPTION
**Pull request by ramperher**
build-depends: https://github.com/rh-nfv-int/nfv-example-cnf-deploy/pull/52
build-depends: https://github.com/dci-labs/dallas-config/pull/125
build-depends: https://github.com/openshift-kni/example-cnf/pull/62

### CODE REVIEW

**Comment by ramperher** [comment]
Something weird is happening when using more than one SRIOV network in cnf_app_networks and packet_generator_networks, and I have the impression that controller-managers are not handling correctly this kind of variables, I need more logs to troubleshoot, so creating https://github.com/openshift-kni/example-cnf/pull/62 for that purpose

**Comment by ramperher** [comment]
> Something weird is happening when using more than one SRIOV network in cnf_app_networks and packet_generator_networks, and I have the impression that controller-managers are not handling correctly this kind of variables, I need more logs to troubleshoot, so creating [openshift-kni/example-cnf#62](https://github.com/openshift-kni/example-cnf/pull/62) for that purpose
> 
> I've seen this after just taking a look to the loadbalancer pod specs:
> 
> ```
>                 "resources": {
>                     "limits": {
>                         "cpu": "10",
>                         "hugepages-1Gi": "16Gi",
>                         "memory": "20Gi",
>                         "openshift.io/intel_numa0_res1": "1",
>                         "openshift.io/intel_numa0_res2": "1"
>                     },
>                     "requests": {
>                         "cpu": "10",
>                         "hugepages-1Gi": "16Gi",
>                         "memory": "20Gi",
>                         "openshift.io/intel_numa0_res1": "1",
>                         "openshift.io/intel_numa0_res2": "1"
>                     }
>                 },
> ```
> 
> we're missing here res3/4, and they should be added by the automation, I've seen we're generating properly the variables in example-cnf hooks, but it's like controller-manager ansible tasks are not working fine. I'll try to confirm that with the logs and, in case this is happening, I'll try to find a workaround for the case where we have two different networks

The issue was on example-cnf, our network-parse doesn't currently support the usage of multiple network resources, I've added it in a new commit in https://github.com/openshift-kni/example-cnf/pull/62, and I've also updated https://github.com/rh-nfv-int/nfv-example-cnf-deploy/pull/52 to remove the check that makes the job to fail in case multiple resources are used

**Comment by ramperher** [comment]
Tested in cluster3, config is now working fine with the latest commits in the other changes, in terms of network interfaces: https://www.distributed-ci.io/jobs/28ee526e-6516-44c0-9173-b62d3ac5da28/jobStates

```
$ oc describe pod loadbalancer-f99f9f776-cndt8
Annotations:      k8s.ovn.org/pod-networks:
                    {"default":{"ip_addresses":["10.131.2.116/23","fd02:0:0:8::74/64"],"mac_address":"0a:58:0a:83:02:74","gateway_ips":["10.131.2.1","fd02:0:0...
                  k8s.v1.cni.cncf.io/network-status:
                    [{
                        "name": "ovn-kubernetes",
                        "interface": "eth0",
                        "ips": [
                            "10.131.2.116",
                            "fd02:0:0:8::74"
                        ],
                        "mac": "0a:58:0a:83:02:74",
                        "default": true,
                        "dns": {}
                    },{
                        "name": "example-cnf/intel-numa0-net3",
                        "interface": "net1",
                        "mac": "40:04:0f:f1:89:01",
                        "dns": {},
                        "device-info": {
                            "type": "pci",
                            "version": "1.1.0",
                            "pci": {
                                "pci-address": "0000:37:0a.5"
                            }
                        }
                    },{
                        "name": "example-cnf/intel-numa0-net4",
                        "interface": "net2",
                        "mac": "40:04:0f:f1:89:02",
                        "dns": {},
                        "device-info": {
                            "type": "pci",
                            "version": "1.1.0",
                            "pci": {
                                "pci-address": "0000:37:0b.0"
                            }
                        }
                    },{
                        "name": "example-cnf/intel-numa0-net1",
                        "interface": "net3",
                        "mac": "60:04:0f:f1:89:01",
                        "dns": {},
                        "device-info": {
                            "type": "pci",
                            "version": "1.1.0",
                            "pci": {
                                "pci-address": "0000:37:02.6"
                            }
                        }
                    },{
                        "name": "example-cnf/intel-numa0-net2",
                        "interface": "net4",
                        "mac": "60:04:0f:f1:89:02",
                        "dns": {},
                        "device-info": {
                            "type": "pci",
                            "version": "1.1.0",
                            "pci": {
                                "pci-address": "0000:37:03.5"
                            }
                        }
                    }]
                  k8s.v1.cni.cncf.io/networks:
                    [ { "name": "intel-numa0-net3", "mac": "40:04:0f:f1:89:01", "namespace": "example-cnf" },          { "name": "intel-numa0-net4", "mac": "4...

$ oc describe pod testpmd-app-77c5d58685-5ssjq
Annotations:      k8s.ovn.org/pod-networks:
                    {"default":{"ip_addresses":["10.130.2.145/23","fd02:0:0:7::91/64"],"mac_address":"0a:58:0a:82:02:91","gateway_ips":["10.130.2.1","fd02:0:0...
                  k8s.v1.cni.cncf.io/network-status:
                    [{
                        "name": "ovn-kubernetes",
                        "interface": "eth0",
                        "ips": [
                            "10.130.2.145",
                            "fd02:0:0:7::91"
                        ],
                        "mac": "0a:58:0a:82:02:91",
                        "default": true,
                        "dns": {}
                    },{
                        "name": "example-cnf/intel-numa0-net1",
                        "interface": "net1",
                        "mac": "da:a3:72:ed:85:5d",
                        "dns": {},
                        "device-info": {
                            "type": "pci",
                            "version": "1.1.0",
                            "pci": {
                                "pci-address": "0000:37:02.4"
                            }
                        }
                    },{
                        "name": "example-cnf/intel-numa0-net2",
                        "interface": "net2",
                        "mac": "0a:d4:3a:f1:f8:88",
                        "dns": {},
                        "device-info": {
                            "type": "pci",
                            "version": "1.1.0",
                            "pci": {
                                "pci-address": "0000:37:03.6"
                            }
                        }
                    }]
                  k8s.v1.cni.cncf.io/networks:
                    [ { "name": "intel-numa0-net1", "namespace": "example-cnf" },          { "name": "intel-numa0-net2", "namespace": "example-cnf" }        ]

$ oc describe pod testpmd-app-77c5d58685-smh6p
Annotations:      k8s.ovn.org/pod-networks:
                    {"default":{"ip_addresses":["10.129.3.11/23","fd02:0:0:6::10b/64"],"mac_address":"0a:58:0a:81:03:0b","gateway_ips":["10.129.2.1","fd02:0:0...
                  k8s.v1.cni.cncf.io/network-status:
                    [{
                        "name": "ovn-kubernetes",
                        "interface": "eth0",
                        "ips": [
                            "10.129.3.11",
                            "fd02:0:0:6::10b"
                        ],
                        "mac": "0a:58:0a:81:03:0b",
                        "default": true,
                        "dns": {}
                    },{
                        "name": "example-cnf/intel-numa0-net1",
                        "interface": "net1",
                        "mac": "4e:54:c0:3e:50:83",
                        "dns": {},
                        "device-info": {
                            "type": "pci",
                            "version": "1.1.0",
                            "pci": {
                                "pci-address": "0000:37:03.1"
                            }
                        }
                    },{
                        "name": "example-cnf/intel-numa0-net2",
                        "interface": "net2",
                        "mac": "c6:02:b5:f3:6a:1f",
                        "dns": {},
                        "device-info": {
                            "type": "pci",
                            "version": "1.1.0",
                            "pci": {
                                "pci-address": "0000:37:02.2"
                            }
                        }
                    }]
                  k8s.v1.cni.cncf.io/networks:
                    [ { "name": "intel-numa0-net1", "namespace": "example-cnf" },          { "name": "intel-numa0-net2", "namespace": "example-cnf" }        ]
```

However, it will fail in the cnfappmac check, it looks like the Golang code used in the cnf-app-mac-operator is not adapted to this new data structure, I need to take a look to that

**Comment by ramperher** [comment]
This change is now working and it's ready for review

**Comment by ramperher** [comment]
Don't pay attention to the red check below, last jobs passed

**Review by capolrik — APPROVED** [review]

**Pull request merged**
