### PR TITLE
Use mirror-catalog from the dci-openshift-agent

### PR DESCRIPTION
**Pull request by tonyskapunk**
The dci-openshift-agent common-roles are provided to the dci-openshift-app-agent, instead of using custom roles, reuse the common-roles when possible

### CODE REVIEW

**Comment by tonyskapunk** [comment]
check dallas ocp-4.11-vanilla example-cnf

**Comment by tonyskapunk** [comment]
check dallas ocp-4.13-vanilla example-cnf

**Comment by ramperher** [comment]
Change looks fine, but it seems that example-cnf components for OCP 4.13 are somehow missed:

```
$ less ~/.dci-queue/log/8nodes/9252
...
2023-01-18 04:21:34,368 - dcipipeline.main - INFO - Setting topic to OCP-4.13 for example-cnf from previous topic
2023-01-18 04:21:34,369 - dcipipeline.main - INFO - scheduling job example-cnf on topic OCP-4.13 previous_job_id=96f8537b-40a5-44aa-b064-c3d08a01f4d7 pipeline_id=4e8981c6-a32d-4a3a-9fcf-ca8133e416a9
2023-01-18 04:21:34,612 - dcipipeline.main - INFO - Got comp query result: nfv-example-cnf-index[type:nfv-example-cnf-index,name:v0.3.1]: {'_meta': {'count': 0}, 'components': []}
2023-01-18 04:21:34,612 - dcipipeline.main - ERROR - No nfv-example-cnf-index[type:nfv-example-cnf-index,name:v0.3.1] component, topic_id 85d5c4ac-3c04-4eaf-9d4c-0af76f6e1c35
2023-01-18 04:21:34,612 - dcipipeline.main - ERROR - Unable to get all components 0 out of 1: []
2023-01-18 04:21:34,612 - dcipipeline.main - ERROR - Unable to schedule job example-cnf. Skipping
2023-01-18 04:21:34,613 - dcipipeline.main - ERROR - 1 job in error at jobdef cnf
2023-01-18 04:21:34,613 - dcipipeline.main - ERROR - No job_info found for jobdef example-cnf
2023-01-18 04:21:34,613 - dcipipeline.main - ERROR - No job.jobstate found for jobdef example-cnf
...
```

**Comment by tkrishtop** [comment]
check dallas ocp-4.10-vanilla example-cnf

**Review by tkrishtop — APPROVED** [review]
Hi Tony, I tested on 4.10 and the mirroring works fine on images that are already mirrored, so the change won't cause any harm for the dailies. I'll merge your change to test with an image that hasn't been mirrored yet: https://github.com/dci-labs/example-cnf-config/pull/61

**Pull request merged**
