### PR TITLE
DNM: Using branch 'fix_retry_issue' for checks

### PR DESCRIPTION
**Pull request by krsacme**

### CODE REVIEW

**Comment by tonyskapunk** [comment]
ocp-4.8-vanilla example-cnf

**Comment by tonyskapunk** [comment]
check dallas ocp-4.8-vanilla example-cnf

**Comment by tonyskapunk** [comment]
check dallas ocp-4.8-vanilla example-cnf

**Comment by krsacme** [comment]
check dallas ocp-4.8-vanilla example-cnf

**Pull request closed without merging**
