### PR TITLE
Using the OC clients defined by DOAA

### PR DESCRIPTION
**Pull request by betoredhat**
- Using the clients used by DOAA
- Information about OCP version is provided by the agent already
- The check for 4.5 is not needed anymore as it is unsupported

build-depends: 24117

### CODE REVIEW

**Comment by ramperher** [comment]
Two things here:

- Where is `app_agent_dir` variable defined?
- In [testpmd/hooks/files/collect-sriov-operator-data.sh](https://github.com/dci-labs/example-cnf-config/pull/47/files#diff-69d5cc7637c91da1374e7abf10e861e90f5d722d93fb9451786762a7a2b72113), I think the script will fail because it cannot render an Ansible variable. We can have a template, .sh.j2, and generate the proper .sh based on the variables included in the .j2, or pass the Ansible variable as argument and change {{ app_agent_dir }} for $1.

**Comment by betoredhat** [comment]
> Two things here:
> 
>     * I saw https://softwarefactory-project.io/r/c/dci-openshift-app-agent/+/24117 is defining `app_agent_dir` and it includes this change as build-depends. Maybe it's better to do it in the opposite way: to have the build-depends: 24117 instead. I think it is better because, in the other way, it will appear in the final commit the reference to example-cnf-config, which is a private repository, but in the opposite case, it will appear the link to 24117, which is public.
> 
>     * In [testpmd/hooks/files/collect-sriov-operator-data.sh](https://github.com/dci-labs/example-cnf-config/pull/47/files#diff-69d5cc7637c91da1374e7abf10e861e90f5d722d93fb9451786762a7a2b72113), I think the script will fail because it cannot render an Ansible variable. We can have a template, .sh.j2, and generate the proper .sh based on the variables included in the .j2, or pass the Ansible variable as argument and change {{ app_agent_dir }} for $1.

Thanks, Ramón, I have updated the dependencies. 

Regarding the shell script, I think that using the shell module will take care of rendering the variables inside the script. Will check.

**Review by manurodriguez — COMMENTED** [review]
I see the job is on the queue, this looks good to me but I'll wait for the results.

**Review by tkrishtop — CHANGES_REQUESTED** [review]

**Comment by betoredhat** [comment]
check dallas ocp-4.9-vanilla

**Comment by betoredhat** [comment]
check dallas ocp-4.9-vanilla

**Comment by betoredhat** [comment]
check dallas ocp-4.9-vanilla

**Comment by betoredhat** [comment]
check dallas ocp-4.9-vanilla example-cnf

**Review by tonyskapunk — APPROVED** [review]
:+1:

**Pull request merged**
