### PR TITLE
Add MCP workaround to fix possible SchedulingDisabled workers

### PR DESCRIPTION
**Pull request by tkrishtop**

### CODE REVIEW

**Review by manurodriguez — COMMENTED** [review]
Tatiana, thanks for starting this, I'll create a PR in the pipelines repo to modify the example-cnf-pipeline and include bz2053445 in the dci_workarounds, but I'll ask again to the team if we better rename that BZ ID since it's closed and we could use one more recent.

**Comment by ramperher** [comment]
The change looks nice, let's see if it works.

Moreover, regarding what @manurodriguez commented, yes, I'd say to change bz2053445 for a more recent one, but let's discuss it.

**Comment by tkrishtop** [comment]
Tested ok, ready to be merged: https://www.distributed-ci.io/jobs/043f2436-fcc1-4a4d-8bd8-10c07b4648fa/jobStates

**Review by capolrik — APPROVED** [review]
LGTM

**Review by ramperher — APPROVED** [review]

**Review by manurodriguez — APPROVED** [review]

**Comment by manurodriguez** [comment]
Tatiana, Ramon updated the example-cnf-pipeline and include bz2053445 in https://github.com/dci-labs/dallas-pipelines/pull/287, so we should be good to merge this.

**Comment by ramperher** [comment]
> Tatiana, Ramon updated the example-cnf-pipeline and include bz2053445 in [dci-labs/dallas-pipelines#287](https://github.com/dci-labs/dallas-pipelines/pull/287), so we should be good to merge this.

Yes, it's true, bz2053445 has been updated in all pipelines, so we can go on with this merge

**Pull request merged**
