### PR TITLE
Perform tnf labelling with k8s module tasks. Omit removal of labels

### PR DESCRIPTION
**Pull request by ramperher**
- Now, tnf labelling tasks are done by following k8s modules instead of shell module, similarly to what was done in [this change](https://softwarefactory-project.io/r/c/dci-openshift-app-agent/+/25172).
- Removal of tnf labels is not going to be done, as the resources are deleted on teardown, following the same approach than tnf_test_example, and to avoid issues (e.g. CILAB-511)

### CODE REVIEW

**Comment by ramperher** [comment]
check dallas ocp-4.8-vanilla example-cnf

**Comment by ramperher** [comment]
check dallas ocp-4.8-vanilla example-cnf openshift-vanilla:ansible_extravars=cnf_test_suites:[]

**Comment by ramperher** [comment]
check dallas ocp-4.8-vanilla example-cnf openshift-vanilla:ansible_extravars=cnf_test_suites:[]

**Comment by ramperher** [comment]
check dallas ocp-4.8-vanilla example-cnf openshift-vanilla:ansible_extravars=cnf_test_suites:[]

**Comment by ramperher** [comment]
check dallas ocp-4.8-vanilla example-cnf openshift-vanilla:ansible_extravars=cnf_test_suites:[]

**Comment by ramperher** [comment]
> * FAILURE https://www.distributed-ci.io/jobs/88b70467-1860-4cd8-a38b-65181331a4c8/jobStates
>   from [Perform tnf labelling with k8s module tasks. Omit removal of labels #59](https://github.com/dci-labs/example-cnf-config/pull/59)

You can see here that the cnf-cert tasks are working fine, with the same results than in daily jobs (e.g. https://www.distributed-ci.io/jobs/b818b68f-e5b8-41b6-a5ae-6848bd973b2c/jobStates). You can see here the tasks that worked and are related to this change: https://www.distributed-ci.io/jobs/88b70467-1860-4cd8-a38b-65181331a4c8/jobStates#de0f3430-59bc-4518-97d7-8aa40fe99da4:file72, so this is ready for merging.

**Comment by ramperher** [comment]
CC @tonyskapunk @betoredhat @manurodriguez , if you can take a look to it, it is an easy one

**Review by manurodriguez — APPROVED** [review]
Thanks Ramon, just a question, I see we include a label now in the CSV and from the doc it reads `CSVs to be tested by the operator and affiliated-certification` Do you know exactly what that means? Will CNF cert suite will check if the operator has been certified?

**Comment by ramperher** [comment]
> Thanks Ramon, just a question, I see we include a label now in the CSV and from the doc it reads `CSVs to be tested by the operator and affiliated-certification` Do you know exactly what that means? Will CNF cert suite will check if the operator has been certified?

Hi Manuel, sure, it means that the CSVs that are labelled will be only tested by the operator and the affiliated-certification test suites. In our pipelines, we are only enabling the operator test suite for the moment, the affiliated-certification one (which checks operator certification) is not currently being used but I intend to include it, it's under track in CILAB-666

**Pull request merged**
