### PR TITLE
adding opcap checks at the tests stage

### PR DESCRIPTION
**Pull request by capolrik**

### CODE REVIEW

**Comment by capolrik** [comment]
check dallas ocp-4.10-vanilla openshift-vanilla:ansible_extravars=cnf_test_suites:[] example-cnf

**Comment by capolrik** [comment]
check dallas ocp-4.10-vanilla openshift-vanilla:ansible_extravars=cnf_test_suites:[] example-cnf

**Comment by capolrik** [comment]
check dallas ocp-4.10-vanilla openshift-vanilla:ansible_extravars=cnf_test_suites:[] example-cnf

**Review by ramperher — APPROVED** [review]
I believe the results are fine

**Pull request merged**
